# Generated by Django 5.1.1 on 2024-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
