# Generated by Django 5.1.1 on 2024-09-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0003_alter_payment_payer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ammount',
            new_name='amount',
        ),
    ]
