# Generated by Django 5.1.1 on 2024-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0004_rename_ammount_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
