# Generated by Django 5.1.1 on 2024-09-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warikan', '0007_event_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
