# Generated by Django 5.1.1 on 2024-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_with_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
